require("statemachine")

-- TODO: boot animation

global function stateBootInit(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateBootEnter(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateBootExit(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateBootUpdate(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateBootDraw(sm: *StateMachine, vm: *e3d.EVM): void
end
