require("statemachine")

-- TODO: add basic ui to load model files

global function stateModelInit(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateModelEnter(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateModelExit(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateModelUpdate(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateModelDraw(sm: *StateMachine, vm: *e3d.EVM): void
end
