require("statemachine")

-- TODO: add basic ui to load model files

global function stateModelInit(sm: *StateMachine, vm: *EVM): void
end

global function stateModelEnter(sm: *StateMachine, vm: *EVM): void
end

global function stateModelExit(sm: *StateMachine, vm: *EVM): void
end

global function stateModelUpdate(sm: *StateMachine, vm: *EVM): void
end

global function stateModelDraw(sm: *StateMachine, vm: *EVM): void
end

global function stateModelCleanup(sm: *StateMachine, vm: *EVM): void
end
