require("statemachine")

-- TODO: boot animation

global function stateBootInit(sm: *StateMachine, vm: *EVM): void
end

global function stateBootEnter(sm: *StateMachine, vm: *EVM): void
end

global function stateBootExit(sm: *StateMachine, vm: *EVM): void
end

global function stateBootUpdate(sm: *StateMachine, vm: *EVM): void
end

global function stateBootDraw(sm: *StateMachine, vm: *EVM): void
end
