require("statemachine")

-- TODO: add basic ui to load texture files

global function stateTextureInit(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateTextureEnter(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateTextureExit(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateTextureUpdate(sm: *StateMachine, vm: *e3d.EVM): void
end

global function stateTextureDraw(sm: *StateMachine, vm: *e3d.EVM): void
end
